const PREC = {
  TYPE_OPERATOR: 1,
  TYPE_FUNCTION: 2,
  PAIR: 1,
  BLOCK: 2,
  IMPLIES: 3,
  LEADS_TO: 4,
  IFF: 5,
  OR: 6,
  AND: 7,
  ASSIGN: 8,
  COMPARE: 9,
  ADD: 10,
  MULTIPLY: 11,
  UNARY: 12,
  POWER: 13,
  POSTFIX: 14,
}

module.exports = grammar({
  name: 'quint',

  extras: $ => [/\s/, $.comment],

  externals: $ => [$.hash_bang_line, $._file_start],

  conflicts: $ => [
    [$.tuple_type, $.operator_type],
    // `(x, y)` is a tuple until a following `=>` makes it a lambda parameter list.
    [$._expression_name, $._lambda_parameter],
    // `((x, y)) =>` is Quint's tuple-parameter sugar, not a grouped tuple value.
    [$.tuple_parameter],
  ],

  word: $ => $.identifier,

  rules: {
    source_file: $ => seq(choice($.hash_bang_line, $._file_start), repeat($.module)),
    module: $ => seq(
      'module',
      field('name', choice($.identifier, $.type_identifier)),
      '{',
      field('body', repeat($._declaration)),
      '}',
    ),
    _declaration: $ => choice(
      $.const_declaration,
      $.var_declaration,
      $.assume_declaration,
      $.operator_definition,
      $.type_declaration,
      $.import_declaration,
      $.export_declaration,
      $.instance_declaration,
    ),
    const_declaration: $ => seq(
      'const',
      field('name', choice($.identifier, $.type_identifier)),
      ':',
      field('type', $._type),
      optional(';'),
    ),
    var_declaration: $ => seq(
      'var',
      field('name', $.identifier),
      ':',
      field('type', $._type),
      optional(';'),
    ),
    assume_declaration: $ => seq(
      'assume',
      field('name', $.identifier),
      '=',
      field('value', $._expression),
      optional(';'),
    ),
    operator_definition: $ => choice(
      seq(
        field('qualifier', $.operator_qualifier),
        field('name', $.identifier),
        field('parameters', alias($._annotated_parameter_list, $.parameter_list)),
        ':',
        field('type', $._type),
        optional(seq('=', field('body', $._expression))),
        optional(';'),
      ),
      seq(
        field('qualifier', $.operator_qualifier),
        field('name', $.identifier),
        optional(field('parameters', alias($._untyped_parameter_list, $.parameter_list))),
        optional(seq(':', field('type', $._type))),
        optional(seq('=', field('body', $._expression))),
        optional(';'),
      ),
    ),
    operator_qualifier: _ => choice(
      'val',
      'def',
      seq('pure', 'val'),
      seq('pure', 'def'),
      'action',
      'run',
      'temporal',
      'nondet',
    ),
    parameter_list: $ => choice(
      $._annotated_parameter_list,
      $._untyped_parameter_list,
    ),
    _annotated_parameter_list: $ => seq(
      '(',
      alias($._annotated_parameter, $.parameter),
      repeat(seq(',', alias($._annotated_parameter, $.parameter))),
      optional(','),
      ')',
    ),
    _untyped_parameter_list: $ => seq(
      '(',
      optional(seq(
        alias($._untyped_parameter, $.parameter),
        repeat(seq(',', alias($._untyped_parameter, $.parameter))),
        optional(','),
      )),
      ')',
    ),
    parameter: $ => choice(
      $._annotated_parameter,
      $._untyped_parameter,
    ),
    _annotated_parameter: $ => seq(
      field('name', $.identifier),
      ':',
      field('type', $._type),
    ),
    _untyped_parameter: $ => field('name', $.identifier),
    type_declaration: $ => choice(
      seq(
        'type',
        field('name', $.qualified_name),
      ),
      seq(
        'type',
        field('name', $.qualified_name),
        optional(seq(
          '[',
          field('type_parameter', $.identifier),
          repeat(seq(',', field('type_parameter', $.identifier))),
          ']',
        )),
        '=',
        field('value', choice($.sum_type, $._type)),
      ),
    ),
    import_declaration: $ => choice(
      seq(
        'import',
        field('module', $.qualified_name),
        '.',
        field('member', choice($.qualified_name, $.wildcard)),
        optional(seq('from', field('source', $.string))),
      ),
      seq(
        'import',
        field('module', $.qualified_name),
        optional(seq('as', field('alias', $.qualified_name))),
        optional(seq('from', field('source', $.string))),
      ),
    ),
    export_declaration: $ => choice(
      seq(
        'export',
        field('module', $.qualified_name),
        '.',
        field('member', choice($.qualified_name, $.wildcard)),
      ),
      seq(
        'export',
        field('module', $.qualified_name),
        optional(seq('as', field('alias', $.qualified_name))),
      ),
    ),
    instance_declaration: $ => seq(
      'import',
      field('module', $.qualified_name),
      field('overrides', $.instance_overrides),
      choice(
        seq('.', field('member', $.wildcard)),
        seq('as', field('alias', $.qualified_name)),
      ),
      optional(seq('from', field('source', $.string))),
    ),
    instance_overrides: $ => seq(
      '(',
      $.instance_override,
      repeat(seq(',', $.instance_override)),
      optional(','),
      ')',
    ),
    instance_override: $ => seq(
      field('name', $.qualified_name),
      '=',
      field('value', $._expression),
    ),
    wildcard: _ => choice('*', '_'),
    _type: $ => choice(
      $.operator_type,
      $.function_type,
      $._type_atom,
    ),
    _type_atom: $ => choice(
      $.primitive_type,
      $.named_type,
      $.type_application,
      $.tuple_type,
      $.record_type,
      $.parenthesized_type,
    ),
    primitive_type: _ => choice('bool', 'int', 'str'),
    named_type: $ => seq(
      choice($.identifier, $.type_identifier),
      repeat(seq('::', choice($.identifier, $.type_identifier))),
    ),
    type_application: $ => choice(
      seq(
        field('name', alias('Set', $.named_type)),
        '[',
        field('argument', $._type),
        ']',
      ),
      seq(
        field('name', alias('List', $.named_type)),
        '[',
        field('argument', $._type),
        ']',
      ),
      seq(
        field('name', $.named_type),
        '[',
        field('argument', $._type),
        repeat(seq(',', field('argument', $._type))),
        ']',
      ),
    ),
    tuple_type: $ => choice(
      seq('(', ')'),
      seq(
        '(',
        field('element', $._type),
        ',',
        field('element', $._type),
        repeat(seq(',', field('element', $._type))),
        optional(','),
        ')',
      ),
    ),
    record_type: $ => seq(
      '{',
      optional(choice(
        seq(
          $.record_field,
          repeat(seq(',', $.record_field)),
          optional(choice(
            ',',
            seq('|', field('tail', $.identifier)),
          )),
        ),
        seq('|', field('tail', $.identifier)),
      )),
      '}',
    ),
    record_field: $ => seq(
      field('name', choice($.identifier, $.type_identifier)),
      ':',
      field('type', $._type),
    ),
    function_type: $ => prec.right(PREC.TYPE_FUNCTION, seq(
      field('parameter', $._type_atom),
      '->',
      field('result', choice($.function_type, $._type_atom)),
    )),
    operator_type: $ => prec.right(PREC.TYPE_OPERATOR, choice(
      seq(
        '(',
        optional(seq(
          field('parameter', $._type),
          repeat(seq(',', field('parameter', $._type))),
          optional(','),
        )),
        ')',
        '=>',
        field('result', $._type),
      ),
      seq(
        field('parameter', choice(
          $.function_type,
          $.primitive_type,
          $.named_type,
          $.type_application,
          $.record_type,
        )),
        '=>',
        field('result', $._type),
      ),
    )),
    parenthesized_type: $ => seq(
      '(',
      field('type', $._type),
      ')',
    ),
    sum_type: $ => choice(
      seq(
        optional('|'),
        $.sum_variant,
        repeat1(seq('|', $.sum_variant)),
      ),
      seq(
        '|',
        $.sum_variant,
      ),
      alias($._sum_variant_with_payload, $.sum_variant),
    ),
    sum_variant: $ => seq(
      field('name', choice($.identifier, $.type_identifier)),
      optional(seq('(', field('type', $._type), ')')),
    ),
    _sum_variant_with_payload: $ => seq(
      field('name', choice($.identifier, $.type_identifier)),
      '(',
      field('type', $._type),
      ')',
    ),
    _expression: $ => choice(
      $._expression_name,
      $.integer,
      $.string,
      $.boolean,
      $.unit_expression,
      $.parenthesized_expression,
      $.tuple_expression,
      $.list_expression,
      $.record_expression,
      $.conditional_expression,
      $.lambda_expression,
      $.unary_expression,
      $.binary_expression,
      $.pair_expression,
      $.delayed_assignment,
      $.call_expression,
      $.ufcs_expression,
      $.field_access_expression,
      $.index_expression,
      $.logical_block,
      $.action_block,
      $.block_expression,
    ),
    _expression_name: $ => choice(
      $.identifier,
      $.type_identifier,
      alias($._qualified_expression_name, $.qualified_name),
    ),
    _qualified_expression_name: $ => seq(
      choice($.identifier, $.type_identifier),
      repeat1(seq('::', choice($.identifier, $.type_identifier))),
    ),
    unit_expression: _ => seq('(', ')'),
    parenthesized_expression: $ => seq('(', $._expression, ')'),
    tuple_expression: $ => seq(
      '(',
      field('element', $._expression),
      ',',
      field('element', $._expression),
      repeat(seq(',', field('element', $._expression))),
      optional(','),
      ')',
    ),
    list_expression: $ => seq(
      '[',
      optional(seq(
        field('element', $._expression),
        repeat(seq(',', field('element', $._expression))),
        optional(','),
      )),
      ']',
    ),
    record_expression: $ => seq(
      '{',
      $.record_element,
      repeat(seq(',', $.record_element)),
      optional(','),
      '}',
    ),
    record_element: $ => choice(
      seq(
        field('name', choice($.identifier, $.type_identifier)),
        ':',
        field('value', $._expression),
      ),
      seq('...', field('value', $._expression)),
    ),
    conditional_expression: $ => seq(
      'if',
      '(',
      field('condition', $._expression),
      ')',
      field('consequence', $._expression),
      'else',
      field('alternative', $._expression),
    ),
    lambda_expression: $ => choice(
      seq(
        field('parameter', alias($._lambda_parameter, $.parameter)),
        '=>',
        field('body', $._expression),
      ),
      seq(
        field('parameters', alias($._lambda_parameter_list, $.parameter_list)),
        '=>',
        field('body', $._expression),
      ),
      seq(
        field('parameters', $.tuple_parameter),
        '=>',
        field('body', $._expression),
      ),
    ),
    _lambda_parameter: $ => field('name', choice($.identifier, $.type_identifier, $.wildcard)),
    _lambda_parameter_list: $ => seq(
      '(',
      alias($._lambda_parameter, $.parameter),
      repeat(seq(',', alias($._lambda_parameter, $.parameter))),
      ')',
    ),
    tuple_parameter: $ => seq(
      '(',
      '(',
      alias($._lambda_parameter, $.parameter),
      ',',
      alias($._lambda_parameter, $.parameter),
      repeat(seq(',', alias($._lambda_parameter, $.parameter))),
      ')',
      ')',
    ),
    unary_expression: $ => prec(PREC.UNARY, seq(
      '-',
      field('operand', $._expression),
    )),
    binary_expression: $ => choice(
      prec.right(PREC.POWER, seq(
        field('left', $._expression),
        '^',
        field('right', $._expression),
      )),
      prec.left(PREC.MULTIPLY, seq(
        field('left', $._expression),
        choice('*', '/', '%'),
        field('right', $._expression),
      )),
      prec.left(PREC.ADD, seq(
        field('left', $._expression),
        choice('+', '-'),
        field('right', $._expression),
      )),
      prec.left(PREC.COMPARE, seq(
        field('left', $._expression),
        choice('>', '<', '>=', '<=', '!=', '=='),
        field('right', $._expression),
      )),
      prec.left(PREC.AND, seq(
        field('left', $._expression),
        'and',
        field('right', $._expression),
      )),
      prec.left(PREC.OR, seq(
        field('left', $._expression),
        'or',
        field('right', $._expression),
      )),
      prec.left(PREC.IFF, seq(
        field('left', $._expression),
        'iff',
        field('right', $._expression),
      )),
      prec.left(PREC.LEADS_TO, seq(
        field('left', $._expression),
        'leadsTo',
        field('right', $._expression),
      )),
      prec.left(PREC.IMPLIES, seq(
        field('left', $._expression),
        'implies',
        field('right', $._expression),
      )),
    ),
    pair_expression: $ => prec.left(PREC.PAIR, seq(
      field('key', $._expression),
      '->',
      field('value', $._expression),
    )),
    delayed_assignment: $ => prec.right(PREC.ASSIGN, seq(
      field('name', $._expression_name),
      "'",
      '=',
      field('value', $._expression),
    )),
    call_expression: $ => prec(PREC.POSTFIX, seq(
      field('function', $._call_name),
      field('arguments', $.argument_list),
    )),
    _call_name: $ => prec(1, choice(
      $._expression_name,
      alias(choice('and', 'or', 'iff', 'implies', 'leadsTo'), $.identifier),
      alias(choice('Set', 'List'), $.type_identifier),
    )),
    _member_name: $ => choice(
      $._expression_name,
      alias(choice('and', 'or', 'iff', 'implies', 'leadsTo'), $.identifier),
    ),
    ufcs_expression: $ => prec.left(PREC.POSTFIX, seq(
      field('receiver', $._expression),
      '.',
      field('function', $._member_name),
      field('arguments', $.argument_list),
    )),
    field_access_expression: $ => prec.left(PREC.POSTFIX, seq(
      field('receiver', $._expression),
      '.',
      field('field', $._member_name),
    )),
    index_expression: $ => prec.left(PREC.POSTFIX, seq(
      field('collection', $._expression),
      '[',
      field('index', $._expression),
      ']',
    )),
    argument_list: $ => seq(
      '(',
      optional(seq(
        $._expression,
        repeat(seq(',', $._expression)),
        optional(','),
      )),
      ')',
    ),
    logical_block: $ => seq(
      choice('and', 'or'),
      '{',
      field('body', $._expression),
      repeat(seq(',', field('element', $._expression))),
      optional(','),
      '}',
    ),
    action_block: $ => seq(
      choice('all', 'any'),
      '{',
      field('body', $._expression),
      repeat(seq(',', field('element', $._expression))),
      optional(','),
      '}',
    ),
    block_expression: $ => seq(
      '{',
      field('body', choice($.declaration_expression, $._expression)),
      '}',
    ),
    declaration_expression: $ => prec.right(PREC.BLOCK, seq(
      field('declaration', alias($._local_operator_definition, $.operator_definition)),
      field('body', $._expression),
    )),
    _local_operator_definition: $ => choice(
      seq(
        field('qualifier', $.operator_qualifier),
        field('name', $.identifier),
        field('parameters', alias($._annotated_parameter_list, $.parameter_list)),
        ':',
        field('type', $._type),
        '=',
        field('body', $._expression),
        optional(';'),
      ),
      seq(
        field('qualifier', $.operator_qualifier),
        field('name', $.identifier),
        optional(field('parameters', alias($._untyped_parameter_list, $.parameter_list))),
        optional(seq(':', field('type', $._type))),
        '=',
        field('body', $._expression),
        optional(';'),
      ),
    ),
    identifier: _ => /[a-z][A-Za-z0-9_]*|_[A-Za-z0-9_]+/,
    type_identifier: _ => /[A-Z][A-Za-z0-9_]*/,
    qualified_name: $ => seq(
      choice($.identifier, $.type_identifier),
      repeat(seq('::', choice($.identifier, $.type_identifier))),
    ),
    integer: _ => token(choice(
      /0x[0-9A-Fa-f](?:_?[0-9A-Fa-f])*/,
      /0|[1-9](?:_?[0-9])*/,
    )),
    string: _ => token(seq('"', repeat(/[^"\n]/), '"')),
    boolean: _ => choice('true', 'false'),
    comment: _ => token(choice(
      seq('///', /[^\n]*/),
      seq('//', /[^\n]*/),
      seq('/*', /[^*]*\*+([^/*][^*]*\*+)*/, '/'),
    )),
  },
})
